const REDUX_LOCAL_STORAGE_KEY = 'persistantState'
const DAYS = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
]

const MISSING_CONTEXT_VALUE = 'Missing context'

const CONTEXTS_SCHEMA_CURRENT_VERSION = 2
const ROUTINES_SCHEMA_CURRENT_VERSION = 5
const TASKS_SCHEMA_CURRENT_VERSION = 6
const SETTINGS_SCHEMA_CURRENT_VERSION = 8

const NUMBER_OF_SECONDS_IN_MINUTE = 60
const TASK_COMPLETION_SCORE = 1
const TASK_FAIL_SCORE = 0

export { default as paths } from './paths'
export * from './paths'

export {
  TASK_FAIL_SCORE,
  TASK_COMPLETION_SCORE,
  NUMBER_OF_SECONDS_IN_MINUTE,
  CONTEXTS_SCHEMA_CURRENT_VERSION,
  ROUTINES_SCHEMA_CURRENT_VERSION,
  SETTINGS_SCHEMA_CURRENT_VERSION,
  TASKS_SCHEMA_CURRENT_VERSION,
  DAYS,
  MISSING_CONTEXT_VALUE,
  REDUX_LOCAL_STORAGE_KEY,
}
